# Generated by Django 5.2 on 2025-05-28 10:20

import core_app.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', help_text='max size is 2 MG', upload_to='images/%Y/%m/%d', validators=[core_app.validation.validate_image_size], width_field='width'),
        ),
    ]
