# Generated by Django 5.2 on 2025-05-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_user_options_alter_student_student_image'),
        ('core_app', '0002_alter_image_image'),
        ('course_app', '0006_alter_course_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
