# Generated by Django 5.2 on 2025-05-28 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('category_name', models.CharField(help_text='نام دسته بندی', max_length=255)),
                ('category_slug', models.SlugField(allow_unicode=True, help_text='اسلاگ دسته بندی', max_length=255)),
                ('is_publish', models.BooleanField(default=True, help_text='فعال')),
            ],
            options={
                'db_table': 'category_course',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(help_text='عنوان درس', max_length=100)),
                ('slug', models.SlugField(help_text='شناسه URL', max_length=100, unique=True)),
                ('code', models.CharField(help_text='کد درس', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(help_text='توضیحات درس')),
                ('thumbnail', models.ImageField(help_text='تصویر درس', upload_to='courses/thumbnails/')),
                ('level', models.CharField(choices=[('basic', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='basic', help_text='سطح درس', max_length=20)),
                ('credit', models.PositiveSmallIntegerField(default=1, help_text='واحد درس')),
                ('duration', models.DurationField(help_text='مدت زمان دوره')),
                ('is_active', models.BooleanField(default=True, help_text='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='course_app.category')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
