# Generated by Django 5.2 on 2025-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='اسلاگ دسته بندی', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='شناسه URL', max_length=255, unique=True),
        ),
    ]
