# Generated by Django 5.2 on 2025-05-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
        ('course_app', '0002_alter_category_category_slug_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ForeignKey(help_text='تصویر درس', on_delete=django.db.models.deletion.PROTECT, to='core_app.image'),
        ),
    ]
