# Generated by Django 5.2 on 2025-05-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('created_at',)},
        ),
    ]
