# Generated by Django 5.2 on 2025-05-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_category_options_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='تصویر درس', null=True, upload_to='course/%Y/%m/%d'),
        ),
    ]
