# Generated by Django 5.2 on 2025-05-28 21:56

import core_app.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='تصویر درس', null=True, upload_to='course/%Y/%m/%d', validators=[core_app.validation.validate_image_size]),
        ),
    ]
