# Generated by Django 5.2 on 2025-05-28 09:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('title', models.CharField(help_text='Title of the exam (max 200 characters)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description about the exam', verbose_name='توضیحات')),
                ('time_limit', models.PositiveIntegerField(help_text='Exam duration in minutes')),
                ('passing_score', models.PositiveIntegerField(help_text='Minimum score required to pass the exam (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this exam currently active and available?', verbose_name='فعال')),
                ('creator', models.ForeignKey(help_text='User who created this exam', limit_choices_to=models.Q(('is_staff', True), models.Q(('user_type', 'teacher'), ('is_active', True)), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='exam_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='When the attempt started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the attempt was completed', null=True)),
                ('score', models.FloatField(blank=True, help_text='Final score of this attempt', null=True)),
                ('is_passed', models.BooleanField(default=False, help_text='Did the user pass this attempt?')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the attempt was made')),
                ('exam', models.ForeignKey(help_text='Exam that was attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam_app.exam')),
                ('user', models.ForeignKey(help_text='User who attempted this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_attempt',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('text', models.TextField(help_text='Full text of the question')),
                ('score', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer to this question', validators=[django.core.validators.MinValueValidator(1)])),
                ('exam', models.ForeignKey(help_text='Exam that this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_app.exam')),
                ('image', models.ForeignKey(blank=True, help_text='Optional image related to the question', null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.image')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('text', models.CharField(help_text='Text of the option (max 500 characters)', max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct answer?', verbose_name='پاسخ صحیح')),
                ('question', models.ForeignKey(help_text='Question that this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam_app.question', verbose_name='سوال')),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='When this answer was submitted')),
                ('attempt', models.ForeignKey(help_text='Exam attempt this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='exam_app.examattempt')),
                ('option', models.ForeignKey(help_text='Option that was selected by the user', on_delete=django.db.models.deletion.CASCADE, to='exam_app.option')),
                ('question', models.ForeignKey(help_text='Question that was answered', on_delete=django.db.models.deletion.CASCADE, to='exam_app.question')),
            ],
            options={
                'db_table': 'user_answer',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
