# Generated by Django 5.2 on 2025-05-29 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('title', models.CharField(help_text='عنوان ازمون', max_length=200)),
                ('description', models.TextField(blank=True, help_text='توضیح ازمون')),
                ('time_limit', models.PositiveIntegerField(help_text='مدت زمان')),
                ('exam_type', models.CharField(blank=True, help_text='نوع سوال', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='فعال')),
                ('exam_image', models.ImageField(blank=True, help_text='کاور ازمون', null=True, upload_to='exam_images/%Y/%m/%d')),
                ('creator', models.ForeignKey(help_text='ایجاد کننده', limit_choices_to=models.Q(('is_staff', True), models.Q(('user_type', 'teacher'), ('is_active', True)), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='exam_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, help_text='زمان پایان که کاربر پایان ازمون رو زده هست', null=True)),
                ('score', models.FloatField(blank=True, help_text='نمره', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='ادرس ای پی کاربر')),
                ('result_color', models.CharField(blank=True, help_text='نتیجه ازمون به صورت وضعیت رنگی', max_length=30, null=True)),
                ('exam', models.ForeignKey(help_text='ازمون', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam_app.exam')),
                ('user', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_attempt',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('text', models.TextField(help_text='Full text of the question')),
                ('is_active', models.BooleanField(default=True, help_text='فعال')),
                ('exam', models.ForeignKey(help_text='Exam that this question belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exam_app.exam')),
            ],
            options={
                'db_table': 'question',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('text', models.CharField(help_text='جواب سوال', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='ایا صحیح هست یا خیر')),
                ('question', models.ForeignKey(help_text='سوال', on_delete=django.db.models.deletion.PROTECT, related_name='options', to='exam_app.question')),
            ],
            options={
                'db_table': 'option',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='زمان پاسخ')),
                ('attempt', models.ForeignKey(help_text='شرکت در ازمون', on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='exam_app.examattempt')),
                ('option', models.ForeignKey(help_text='جواب', on_delete=django.db.models.deletion.PROTECT, to='exam_app.option')),
                ('question', models.ForeignKey(help_text='سوال', on_delete=django.db.models.deletion.PROTECT, to='exam_app.question')),
            ],
            options={
                'db_table': 'user_answer',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
