# Generated by Django 5.2 on 2025-05-28 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='passing_score',
        ),
        migrations.AlterField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(help_text='ایجاد کننده', limit_choices_to=models.Q(('is_staff', True), models.Q(('user_type', 'teacher'), ('is_active', True)), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='exam_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح ازمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فعال'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='عنوان ازمون', max_length=200),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Is this the correct answer?'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(help_text='Question that this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam_app.question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(help_text='Text of the option (max 500 characters)', max_length=500),
        ),
    ]
