# Generated by Django 5.2 on 2025-05-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='exam',
        ),
    ]
