# Generated by Django 5.2 on 2025-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_remove_exam_passing_score_alter_exam_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_number',
            field=models.CharField(blank=True, help_text='شماره ازمون', null=True),
        ),
    ]
