# Generated by Django 5.2 on 2025-05-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_remove_useranswer_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answered_at',
        ),
    ]
