# Generated by Django 5.2 on 2025-05-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_exam_exam_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_number',
        ),
    ]
