# Generated by Django 5.2 on 2025-05-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_option_is_correct_useranswer_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='ایا صحیح هست یا خیر'),
        ),
    ]
