# Generated by Django 5.2 on 2025-05-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_exam_exam_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
