# Generated by Django 5.2 on 2025-05-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_remove_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
    ]
