# Generated by Django 5.2 on 2025-05-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_question_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='is_passed',
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='زمان پایان که کاربر پایان ازمون رو زده هست', null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(help_text='ازمون', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam_app.exam'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(blank=True, help_text='نمره', null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
