# Generated by Django 5.2 on 2025-05-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_remove_examattempt_is_passed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='result_color',
            field=models.CharField(blank=True, help_text='نتیجه ازمون به صورت وضعیت رنگی', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='ایا صحیح هست یا خیر'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(help_text='سوال', on_delete=django.db.models.deletion.PROTECT, related_name='options', to='exam_app.question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(help_text='جواب سوال', max_length=500),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='زمان پاسخ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(help_text='شرکت در ازمون', on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='exam_app.examattempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='option',
            field=models.ForeignKey(help_text='جواب', on_delete=django.db.models.deletion.PROTECT, to='exam_app.option'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(help_text='سوال', on_delete=django.db.models.deletion.PROTECT, to='exam_app.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
