# Generated by Django 5.2 on 2025-05-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_alter_option_options_remove_useranswer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_image',
            field=models.ImageField(blank=True, help_text='کاور ازمون', null=True, upload_to='exam_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='ادرس ای پی کاربر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(help_text='Exam that this question belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exam_app.exam'),
        ),
    ]
