# Generated by Django 5.2 on 2025-05-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_exam_exam_image_alter_examattempt_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, help_text='نوع سوال', max_length=20),
        ),
    ]
