# Generated by Django 5.2 on 2025-05-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_start_time',
            field=models.DateTimeField(blank=True, help_text='زمان شروع ازمون؟', null=True),
        ),
    ]
