# Generated by Django 5.2 on 2025-05-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0012_exam_exam_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_start_time',
        ),
    ]
