# Generated by Django 5.2 on 2025-05-29 01:48

import account_app.validators
import core_app.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15, validators=[account_app.validators.PhoneNumberValidator()])),
                ('otp_code', models.CharField(max_length=8)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', help_text='The type of user this is. admin - teacher - student', max_length=10)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[account_app.validators.PhoneNumberValidator()])),
                ('email', models.EmailField(blank=True, max_length=254, validators=[account_app.validators.unique_email_in_layer_app])),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('nation_code', models.CharField(blank=True, max_length=11, validators=[account_app.validators.unique_nation_code_in_layer_app])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('student_number', models.CharField(blank=True, max_length=11)),
                ('student_image', models.ImageField(blank=True, help_text='عکس دانش اموز', null=True, upload_to='student_images/%Y/%m/%d', validators=[core_app.validation.validate_image_size])),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[account_app.validators.PhoneNumberValidator()])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserLoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_logs',
            },
        ),
    ]
