# Generated by Django 5.2 on 2025-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False, help_text='ایا کاربر تایید شده هست'),
        ),
    ]
