# Generated by Django 5.2 on 2025-05-28 21:56

import core_app.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_user_options_alter_student_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, help_text='عکس دانش اموز', null=True, upload_to='student_images/%Y/%m/%d', validators=[core_app.validation.validate_image_size]),
        ),
    ]
