# Generated by Django 5.2 on 2025-05-29 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_student_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=None, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_logs',
            },
        ),
    ]
